[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    title = "Adno"
    titleAddition = "Adno project"
    footer = "<a href='https://emf.fr'>Espace Mendès France</a>, Poitiers - Nouvelle-Aquitaine (France). <br />This project was supported by the <a href='https://www.culture.gouv.fr/Thematiques/Innovation-numerique/Aides-a-l-innovation-et-a-la-transformation-numerique/Culture-et-innovation-numerique-decouvrez-les-laureats-de-l-appel-a-projets-Services-numeriques-innovants'>French Ministry of Culture</a>."

[fr]
  languageName = "French"
  contentDir = "content/fr"
  weight = 12
  [fr.params]
    languageISO = "FR"
    languageTag = "fr-FR"
    title = "Adno"
    titleAddition = "Projet Adno"
    footer = "<a href='https://emf.fr'>Espace Mendès France</a>, Poitiers - Nouvelle-Aquitaine (France). <br />Ce projet a été soutenu par le <a href='https://www.culture.gouv.fr/Thematiques/Innovation-numerique/Aides-a-l-innovation-et-a-la-transformation-numerique/Culture-et-innovation-numerique-decouvrez-les-laureats-de-l-appel-a-projets-Services-numeriques-innovants'>ministère de la Culture</a>."
